# build.yaml

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-python-base:latest
  armv7: ghcr.io/home-assistant/armv7-python-base:latest
  amd64: ghcr.io/home-assistant/amd64-python-base:latest
